### ISSUE TITLE
"Estimate Rate Constants" generating a loop and not finishing

### ISSUE THREAD

**Issue by snguyen49** [RNA-FRETools/MASH-FRET#113]
Hi,

Whenever I try to estimate rate constants, the generation turns into a loop and does not stop unless I close the entire program.

Many Thanks,
Sydney Nguyen

Email: snguyen49@student.gsu.edu

**Comment by snguyen49** [comment]
Hi again,

The system was set to have 100 molecules for 1000 frames with no change in number of states or rate constants. Does this count as a large system? If so, how long would the estimated calculation time be?

Many Thanks,
Sydney Nguyen

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mca-sh** [comment]
Hi Sydney,

Your data set is quite small, but what about the dimension of the model you are trying to fit? How many states are there?
The larger the transition rate matrix, the longer it will take.

Also, sometimes the algorithm needs a long time to converge when the complexity of the transition matrix is too high for the actual data.

To follow the convergence, you can see in the command window the parameter `d` and `dL`. It will stop when `d` becomes lower than 1E-8 or `dL` lower than 1E-6.

Fast convergence happens in about ten minutes, slow convergence in hours.

Best,
Mélodie

**Comment by snguyen49** [comment]
I had set the number of states to just 2 to test out the feature. If it takes at minimum 10 minutes, then I must have not waited long enough as I had thought there was something wrong.

Sydney Nguyen

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mca-sh** [comment]
I see, this is a small system, this should not take long.
Have a look at the progress in the command window when the process is running.

**Comment by snguyen49** [comment]
When I took a look at the progress, it looked as if it was rerunning some of the same calculations. The process command also continuously stated that it was restarting the calculations.

Sydney Nguyen

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mca-sh** [comment]
Yes indeed, the initial transition probabilities are initialized multiple times (five if you did not change the parameters) and the inference yielding the maximum likelihood is selected as the best "fit". 
If this best "fit" transition probability matrix contains very low probabilities, these transition will be forbidden and the calculations are run again until no probability is neglectable.

**Comment by mca-sh** [comment]
Unfortunately you can't be certain to recover the proper transition probabilities as multiple different matrices will yield the exact same data. 
The algorithm gives the least complex estimate of the transition probability matrix that would render the data.

**Comment by mca-sh** [comment]
If it is taking that long for a two-state system, it means that it tries to fit a model that is way too complex for what it is.
I guess you ran ML-DPH to find the number of degenerate states, right?
What is the value of the parameter `D` that it found for both states?
I am pretty sure this value was overestimated by ML-DPH. 

I noticed that overestimation happens when the dwell time distribution shows only one decay.
I will need to find a way to correct this sensitivity.

**Comment by mca-sh** [comment]
While I am trying a workaround, and as you are working with simulated data, you can set the parameter `bin` in panel `Kinetic model` to 1 instead of 10. 
I tried it and it worked, though it will be a bit longer to find the number of states.

**Comment by snguyen49** [comment]
Okay that's perfectly fine with me. Thank you so much!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mca-sh** [comment]
Hi Sidney,
After making tests, it is preferable to use `bin`=1 as long as you are using simulated data. Histogram re-binning has a detrimental effect of the performances of ML-DPH.
Use `bin`=10 only for experimental data.

I've just added an additional test that favors underestimation of the number of degenerate states in case the dwelltime histograms are overbinned (like in your case), so that you don't accidently get caught in an endless estimation of rate constants.
You can find the corrected version in the main Github page, branch master (or here: https://codeload.github.com/RNA-FRETools/MASH-FRET/zip/refs/heads/master).


Thanks again for reporting the issue,
Mélodie
