### ISSUE TITLE
Spotting tool + zoom function issue

### ISSUE THREAD

**Issue by snguyen49** [RNA-FRETools/MASH-FRET#127]
Hi Melodie, 

Thank you for applying the new feature! However, I am getting a new issue with the spotting tool. At first, the spotting looks fine, but when I move the spotting are box(red) in the second channel to the right, the spots on the second channel somehow shift into the first channel. You can see the before and after below.
Before:
![image](https://github.com/RNA-FRETools/MASH-FRET/assets/142941188/304f29b8-7d66-498d-b42f-5cd814433aa8)

After: 
![image](https://github.com/RNA-FRETools/MASH-FRET/assets/142941188/c56eaf7a-4ca7-4f23-a0df-d8b61ab9392b)
and
![image](https://github.com/RNA-FRETools/MASH-FRET/assets/142941188/7ab832de-0dc9-4efe-9fbd-7d4ca6b4b420)

Many Thanks,
Sydney Nguyen
snguyen49@student.gsu.edu

**Comment by mca-sh** [comment]
Hi Sydney and thanx again for reporting an issue.
Oops, yes it seems I did not handle the x-limits properly.
Also, it seems that 500% zoom is not enough for your video, so I increased the maximum zoom to 1000%.
These modifications are included in this version: https://github.com/RNA-FRETools/MASH-FRET/archive/refs/heads/master.zip

I hope it works for you too, otherwise you can open a new issue.
Best,
Mélodie

**Comment by snguyen49** [comment]
Thank you Melodie! 

Best,
Sydney
