### ISSUE TITLE
Poisson SNR characteristics

### ISSUE THREAD

**Issue by snguyen49** [RNA-FRETools/MASH-FRET#129]
Hi Melodie,

I was wondering if this effect is normal. I set my simulation at 2 states with each kinetic rate being 0.1 in sampling steps. I also set my FRET efficiencies as the default State 1 = 0 and State 2 = 1. However, when I set my SNR characteristics to Poisson the time trace and FRET histogram do not indicate FRET efficiencies of 0 and 1. Instead, it concentrates in the middle between 0.4 and 0.6 as seen below. 
![image](https://github.com/RNA-FRETools/MASH-FRET/assets/142941188/57bf5e7b-5439-44ee-b082-fca379dc9a32)
![image](https://github.com/RNA-FRETools/MASH-FRET/assets/142941188/c8988e37-b759-48d9-9511-ba2afc49a963)

I was wondering if this is to be expected. This does not seem to happen with any other SNR characteristic option. However, our camera's SNR is that of Poisson distribution. I was wondering if this effect will occur when I import our raw data into the program and whether this is to be expected or not. 

Many Thanks,
Sydney

**Comment by mca-sh** [comment]
Hi Sydney,

Yes, this is an effect that is expected for `P- or Poisson` and `Offset only`.
For these two noise models, the "offset" is given in photon counts (PC).
By default, the noise offset value is 113 PC, whereas the total count of photons emitted by the fluorophores is 56 PC.
If you did not change these values, your final donor and acceptor signals mainly comprise camera noise.
Actually, $113/(113+56)=66$% of your signal at minimum is camera noise).

Therefore, when calculating apparent $FRET$ for a FRET efficiency $E=0$ you actually have:
$FRET=\frac{I_A}{I_A+I_D}=\frac{offset+E \times I_{tot}}{(offset+E \times I_{tot})+(offset+(1-E) \times I_{tot})}=\frac{113+0 \times 56}{(113+0 \times 56) + (113+1\times 56)}=0.4$

For $E=1$, you have:
$FRET=\frac{113+1 \times 56}{(113+1 \times 56) + (113+0\times 56)}=0.6$

If you want, you can learn more about the calculations of camera noise in the online doc (https://rna-fretools.github.io/MASH-FRET/simulation/components/panel-video-parameters.html#camera-snr-characteristics).

The good news, is that, when applied correctly, the background correction in Trace processing reverses this effect.
If you still have these corrupted FRET values in Trace processing, it is because the background correction is not correctly applied.
I recommend to use the `<N-median values>` method with the `dynamic` option activated.
Be sure that these parameters are set and the box `Apply` is activated for <u>**each data**</u> listed in the popup menu `data`.
Then, apply these parameters to all molecules in your project by pressing `All` and updating all calculations by pressing `UPDATE ALL`.

This should do the job, otherwise please tell me.

Best,
Mélodie

**Comment by snguyen49** [comment]
Thank you!

Sydney

**Comment by mca-sh** [comment]
You are very welcome!
I will close this issue since it seems to be resolved.

Mélodie
