### ISSUE TITLE
MASH- FRET does not calculate traces over the whole channel pictures

### ISSUE THREAD

**Issue by Much756** [RNA-FRETools/MASH-FRET#134]
Hi,

I am just getting started with MASH-FRET (v.1.3.4) and came across the issue, when I was checking my traces in the tracemanager. Apparently traces were only calculated for around 2/3 of the detected spots along the x- dimension of the two channels.

![Screenshot 2024-05-17 110748](https://github.com/RNA-FRETools/MASH-FRET/assets/170084438/6aca65a1-b0d3-4e9d-b747-e3e103bd7d5b)

I think, I was able to track down the error to create_trace.m file line 20, where the dimensions of the resolutions were falsely assigned. 
But I do not know, if this is intended or if I did something wrong while iterating through the calculation steps. 
 
 - Windows 11
 - Matlab Version R2023b
 - MASH-FRET (v.1.3.4)

Best regards,
Michael Kaltenegger

e-mail: michael.kaltenegger@uni-graz.at

**Comment by mca-sh** [comment]
Hello Michael and thank you for the report.

Yes indeed your are right, the bug comes from the wrong assignment of video dimensions at the exact code line you mentioned.
We are not used to video having width unequal to height, so thank you very much for detecting (and fixing!) the bug.

You can find the corrected version here: https://github.com/RNA-FRETools/MASH-FRET/archive/refs/heads/master.zip
or just by `git pull` in your git repository.

Best,
Mélodie
