### ISSUE TITLE
Question about analysis with MASH-FRET

### ISSUE THREAD

**Issue by snguyen49** [RNA-FRETools/MASH-FRET#135]
Hi Melodie,

I was wondering why the program does not let me put in a direct excitation value. Is there something I am supposed to do to enable this?

![image](https://github.com/RNA-FRETools/MASH-FRET/assets/142941188/03216e47-3b87-4044-bb2e-27de9e0459ab)

Many Thanks,
Sydney Nguyen

**Comment by mca-sh** [comment]
Hi Sydney,

[In the doc](https://rna-fretools.github.io/MASH-FRET/trace-processing/workflow.html#cross-talk-correction) you can see that to correct for direct excitation, you need the signal of an emitter upon specific ($ex_0$) and unspecific ($ex \neq ex_0$) laser excitation wavelengths.

Because direct excitation is not available, my guess is that in your [experiment settings](https://rna-fretools.github.io/MASH-FRET/tutorials/set-experiment-settings/import-video.html#lasers):
1. only one laser is defined (continuous excitation), or
2. multiple laser wavelengths are defined (alternating laser excitation) but none is defined as the emitter's specific excitation wavelength (ex: red laser specific to acceptor).

If it is not the case, then something is wrong with the software and I need to correct for it.

Best,
Mélodie

**Comment by snguyen49** [comment]
We are using the typical smFRET format with one laser in continuous excitation. Does that mean that it is supposed to be like this? I had originally thought these values were something I had to calculate manually and apply in MASH-FRET separately for all scenarios.

**Comment by mca-sh** [comment]
The thing is that by convention, the direct excitation is considered to be a non-null acceptor signal collected upon donor excitation (let's say the green laser) in absence of FRET. This happens only because the green laser wavelength is overlapping with the absorption spectrum of the acceptor dye (which ideally should not).
In MASH, to remove this unwanted contribution to the acceptor signal, we use the direct excitation coefficient $DE$ that you calculate from data showing acceptor-only molecules alternatively excited with donor- (green laser) and acceptor-specific (red laser) excitation wavelength, using the formula:
$$DE_{acc}^{green}=\frac{I_{acc}^{green}}{I_{acc}^{red}}$$
where $I_{acc}^{green}$ is the acceptor signal collected upon donor-specific excitation and $I_{acc}^{red}$ upon acceptor-specific excitation.
The coefficient $DE_{acc}^{green}$ is then used in your regular data showing molecules with both donor and acceptor dye labels to correct the acceptor signal from this unwanted contribution using the formula:
$$\left( I_{acc}^{green} \right)^*=I_{acc}^{green}-DE_{acc}^{green} \times I_{acc}^{red}$$
You see here that, **to correct for direct excitation of the acceptor by the green laser, you need data alternatively recorded upon the green ($I_{acc}^{green}$) and red laser ($I_{acc}^{red}$)**. If one of this data is missing, the correction is not available.
In your case, your experiment is performed under continuous excitation, meaning that one of these two signal is missing. Therefore, the direct excitation correction is not available.

I hope this is clear, otherwise don't hesitate to ask for precisions.

Best,
Mélodie

**Comment by snguyen49** [comment]
Ah, that makes a lot more sense. Thank you!


________________________________

**Comment by mca-sh** [comment]
You are welcome!
I will close this issue now.
Don't hesitate to ask more questions.
Best,
Mélodie
