### ISSUE TITLE
Transition probability always stays at 0

### ISSUE THREAD

**Issue by snguyen49** [RNA-FRETools/MASH-FRET#139]
Hi,

I have found recently that the box that should be displaying the transition probabilities is always at 0 regardless of what project I am working on.:
![image](https://github.com/user-attachments/assets/69c39f23-6ef7-4242-9137-572f5bf833a8)

Best,
Sydney Nguyen

**Comment by snguyen49** [comment]
Hi,

I was wondering if there is any update on this?

Best,
Sydney Nguyen

**Comment by mca-sh** [comment]
Hi Sydney,

Sorry for the delayed answer, I am currently in maternity leave and not often on the computer.

This field is actually obsolete, let me explain why.
ML-DPH is using some constrained models to determine the most sufficient number of degenerate states. It tested two minimal models: 1) a model where transitions between degenerate states are forbidden (w=0 for all states) 2) a model where transitions happen from one degenerate state to the next one irreversibly (w=1 for all state to one other and w=0 to the other ones).

In any case, this field does not give real information about your system since it fits a very simple model to ensemble dwelltime histogram. To obtain more accurate transition probabilities, you need to run the Baum-Welch algorithm by pressing `estimate rate constant`

I hope I was not too confusing.
Please come back to me if you have anymore questions.

Best,
Mélodie

**Comment by snguyen49** [comment]
Hi Melodie,

That makes a lot of sense. Thank you so much for the explanation.

Best,
Sydney
________________________________
