### ISSUE TITLE
Managing molecules causing error

### ISSUE THREAD

**Issue by snguyen49** [RNA-FRETools/MASH-FRET#141]
Hi,
When we are managing the molecules in the Trace processing portion, there will be times when we will attempt to look at a molecule (ex: molecule 88) and we recieve an an error like this:
![image](https://github.com/user-attachments/assets/718e52ef-dd17-4bbf-89f6-9aecca50d06e)

This is happening often in other projects. We have also attempted to close and restart, but it is still giving us problems. When this error happen, we are not able to clear any of our excluded selections. We receive this error:
![image](https://github.com/user-attachments/assets/831167d5-c52f-4f15-aebb-8e2e99ca95b0)

The first error also shows up when we try to update the molecules.

Many Thanks,
Sydney Nguyen

**Comment by mca-sh** [comment]
Hi Sydney and thank you for the bug report.

The project seems to be created from trajectory files, is this correct?
**If yes**, did you actually intend to import [FRET state sequences](https://rna-fretools.github.io/MASH-FRET/tutorials/set-experiment-settings/import-trajectories.html#fret-state-sequence-data) from those files?
   - If yes, could you please send me via email (melodiehadzic@protonmail.com) one of those .mash files that is causing such error
   - If not, try to re-create your project and deactivate the option `FRET state columns` in the `File structure` tab of the experiment settings window.

**If not**, please send me via email one of the .mash files that is causing such error, so I can check what is going wrong.

Best,
Mélodie

**Comment by snguyen49** [comment]
Hi Melodie,

Yes, I intended to import the FRET state sequences to specifically refine the data if I find any anomalies that may be related to our equipment errors. Here is the project file.
From working on it a bit more, I found that the errors show up when I clip and split any sequences, I will immediately start running into the exclusion error (the first error) and prevent me from clearing any of the selections.

Many Thanks,
Sydney Nguyen
________________________________

**Comment by mca-sh** [comment]
Hi Sydney,

Thank you for the file.
Indeed there was a mishandling of imported FRET state trajectories when splitting trajectories.
This should now be corrected in the last version downloadable here: https://github.com/RNA-FRETools/MASH-FRET/archive/refs/heads/master.zip
The bad news is that you will have to repeat trace processing including trajectory splitting and sample clearing since imported state trajectories were left untouched, I am sorry for that.
Please tell me if it works for you.

Something else I've noticed in your project:
- sometimes the intensity signals drop below zero, which may tell us that the background correction is not the best: I recommend to use the `dynamic` option in the Background panel in order to calculate the background for each time point in the trajectory ([see doc](https://rna-fretools.github.io/MASH-FRET/trace-processing/components/panel-background-correction.html#background-correction-settings) for more information)
- to use the FRET state trajectories imported from your trajectory files, you need to parametrize the Find state panel such that `method` is set to `imported` ([see doc](https://rna-fretools.github.io/MASH-FRET/trace-processing/components/panel-find-states.html#discretization-method)), otherwise they will be recalculated according to the chosen method.
- by doing so, I've noticed that the "state" trajectories that were imported for this project were raw FRET signals: be sure that the column defined for the `FRET state column` in the `File structure` tab of the experiment settings window is well defined when you import your trajectories ([see doc](https://rna-fretools.github.io/MASH-FRET/tutorials/set-experiment-settings/import-trajectories.html#fret-state-sequence-data))

Best,
Mélodie

**Comment by mca-sh** [comment]
Hi Sydney,

What about this issue? Is it fixed for you?
Best,
Mélodie

**Comment by snguyen49** [comment]
Yes the program you recently sent me is working well!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mca-sh** [comment]
Perfect, thanx. I close this issue then.
