### ISSUE TITLE
Video Processing is not able to open .pma file

### ISSUE THREAD

**Issue by kaura2** [RNA-FRETools/MASH-FRET#64]
**Describe the bug**
I cannot load a .pma video file.  MatLab produces an error code saying 

Error using zeros
Size inputs must be integers.

Error in readPma (line 116)
            h.movie.movie = zeros([pixelY pixelX frameLen]);

**To Reproduce**
1. Go to 'Video Processing'
2. Click on 'Load'
3. Choose any .pma file

**Error Code**
See attachment

**Expected behavior**
I expect for an image to load corresponding to the .pma file so that I may create trace files with a .mash format for further processing.

**Screenshots**

**Desktop (please complete the following information):**
 - OS [Windows 10]
 - Matlab Version [2017a]
 - MASH-FRET Version [1.1.2]

**Additional context**
I am newly trying this software in the hopes of using BOBA FRET for further analysis of histograms.  However, we use the Single.exe software for data acquisition providing video files in the .pma format so I thought to convert my traces by starting with the original video processing.

**Your contact**
kaura2@vcu.edu
![Capture](https://user-images.githubusercontent.com/50523831/78851694-71fcfc00-79e8-11ea-8c61-911f03f28785.JPG)

**Comment by mca-sh** [comment]
Hello kaura2, 
Reading .pma files was not tested since 5 or more years, so thank you for reporting the bug.
May I have a short version of your file or any similar file to fix the error?

**Comment by kaura2** [comment]
Hello!
Thank you for your speedy reply.  Is there an email address that I can send the file to? I am having some trouble attaching the file below.

**Comment by mca-sh** [comment]
Yes, you can use: melodiehadzic@protonmail.com

**Comment by kaura2** [comment]
Thank you. I have sent the a short .pma file to the email address provided.

**Comment by mca-sh** [comment]
Hello kaura2,
Thank you for your cooperation!
The bug is fixed: I tried the common procedure with your file and everything worked from my side.
I will close the issue now (you can download/clone this branch: [https://github.com/RNA-FRETools/MASH-FRET/tree/MASH-code-15](https://github.com/RNA-FRETools/MASH-FRET/tree/MASH-code-15)). Please, do not hesitate to open a new issue if something goes wrong.

If you need help with MASH, you can use the [documentation](https://rna-fretools.github.io/MASH-FRET/). If you can't find the information you need in the documentation, please contact me.
Also, any honest feedback on MASH-FRET (especially from first-timers) are highly appreciated :)
