### ISSUE TITLE
Background-corrected trajectories drop below zero

### ISSUE THREAD

**Issue by nsivan16** [RNA-FRETools/MASH-FRET#93]
**Describe the bug**
After bleaching, the Intensities are too high or too low (not around 0). We are mainly using "N-Median" as the default background correction method. Nonetheless, using a different correction method do not improve the issue. 

**Expected behavior**
After bleaching, the traces should drop around zero. Often the traces drop to a higher or lower value than 0.

**Screenshots**
![image](https://github.com/RNA-FRETools/MASH-FRET/assets/137193584/bd815258-0216-4319-9a8f-d16d47218206)
![image](https://github.com/RNA-FRETools/MASH-FRET/assets/137193584/105537d2-2a83-4d7e-89b2-354d7d594c88)
![image](https://github.com/RNA-FRETools/MASH-FRET/assets/137193584/89bd38d2-0f1d-478a-a5ec-cc2e82f9dd5f)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Matlab Version: R2022b
 - MASH-FRET Version: 1.3.3.1 (prev. commit: 95082dc3)

**Additional context**
The method "Dark traces" solves sometimes the issue, but chooses randomly a spot as reference, where another molecule is.

**Your contact**
nirusan.sivanantharsa@uzh.ch

**Comment by mca-sh** [comment]
Hello Nirusan and thak you for reporting this issue.

We've had this concern many times in the past. 
It most probably comes from a loss of focus in the video sample, or a bleaching fluorescent background.
This is supported by the fact the the "dark trace" background correction (meaning the subtraction of a background-time trace) solves the issue. This method was actually implemented for this type of data.

However, the "dark trace" method should not target other molecules and this must be corrected.
Can you show me a screenshot of such mis-targetting (you can just drag-and-drop it in the writing area)?
I just want to be sure the density of single molecules is not too high.

**Comment by nsivan16** [comment]
Hi Mélodie,

Here are some examples.
![image](https://github.com/RNA-FRETools/MASH-FRET/assets/137193584/ca70d3ba-262d-4d51-a3a8-5ff6e54b8e1e)
![image](https://github.com/RNA-FRETools/MASH-FRET/assets/137193584/9124c220-3134-4ffd-a655-eef9821a5299)
![image](https://github.com/RNA-FRETools/MASH-FRET/assets/137193584/b41c439e-47da-4ffa-b5f8-879b61007d9b)

**Comment by mca-sh** [comment]
Hi Nirusan, thanks for the images.

So it comes from a background signal decreasing in time like we had in the past with the new microscope.

As we will have lots of these data, there is now a `dynamic` checkbox that allows to calculate and subtract a background trajectory with any of the available methods. Like this, you can use the accurate "N median values" method in the "dynamic" mode to get the best correction for this type of data.

Beside, thanks to your remark, I've corrected the way the dark coordinates are automatically found in order to have minimum overlap with any bright signal.

You can find the corrected version here: https://github.com/RNA-FRETools/MASH-FRET/archive/refs/heads/dynamic-bg-corr.zip
Please tell me if it work for you.

Mélodie

**Comment by mca-sh** [comment]
Hi Nirusan,
I will merge these modifications in the main branch. If anything isn't working with them, please reopen this issue.
Mélodie

**Comment by nsivan16** [comment]
Hi Mélodie,

Thanks for the information. I've been using the new version since this week. It works very well. Thank you very much!
I will get back to you if any new problems occur.

Thanks,
Nirusan
________________________________
